version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - thde
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
